// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.10
// 	protoc        v3.14.0
// source: protoBufStack.proto

package proto

import (
	stream "github.com/bhbosman/gocommon/stream"
	goerrors "github.com/bhbosman/goerrors"
	goprotoextra "github.com/bhbosman/goprotoextra"
	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoBufStackMessageInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageData []byte `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
}

func (x *ProtoBufStackMessageInstance) Reset() {
	*x = ProtoBufStackMessageInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoBufStack_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoBufStackMessageInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBufStackMessageInstance) ProtoMessage() {}

func (x *ProtoBufStackMessageInstance) ProtoReflect() protoreflect.Message {
	mi := &file_protoBufStack_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBufStackMessageInstance.ProtoReflect.Descriptor instead.
func (*ProtoBufStackMessageInstance) Descriptor() ([]byte, []int) {
	return file_protoBufStack_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoBufStackMessageInstance) GetMessageData() []byte {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (self *ProtoBufStackMessageInstance) TypeCode() uint32 {
	return ProtoBufStackMessageInstanceTypeCode
}

type ProtoBufStackMultiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*ProtoBufStackMessageInstance `protobuf:"bytes,1,rep,name=Messages,proto3" json:"Messages,omitempty"`
}

func (x *ProtoBufStackMultiMessage) Reset() {
	*x = ProtoBufStackMultiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoBufStack_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoBufStackMultiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBufStackMultiMessage) ProtoMessage() {}

func (x *ProtoBufStackMultiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protoBufStack_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBufStackMultiMessage.ProtoReflect.Descriptor instead.
func (*ProtoBufStackMultiMessage) Descriptor() ([]byte, []int) {
	return file_protoBufStack_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoBufStackMultiMessage) GetMessages() []*ProtoBufStackMessageInstance {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (self *ProtoBufStackMultiMessage) TypeCode() uint32 {
	return ProtoBufStackMultiMessageTypeCode
}

var File_protoBufStack_proto protoreflect.FileDescriptor

var file_protoBufStack_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x1a, 0x20, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40,
	0x0a, 0x1c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x6c, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x53, 0x74, 0x61, 0x63,
	0x6b, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4f, 0x0a,
	0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x33, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66,
	0x53, 0x74, 0x61, 0x63, 0x6b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x42, 0x08,
	0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoBufStack_proto_rawDescOnce sync.Once
	file_protoBufStack_proto_rawDescData = file_protoBufStack_proto_rawDesc
)

func file_protoBufStack_proto_rawDescGZIP() []byte {
	file_protoBufStack_proto_rawDescOnce.Do(func() {
		file_protoBufStack_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoBufStack_proto_rawDescData)
	})
	return file_protoBufStack_proto_rawDescData
}

var file_protoBufStack_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protoBufStack_proto_goTypes = []interface{}{
	(*ProtoBufStackMessageInstance)(nil), // 0: golang.example.policy.ProtoBufStackMessageInstance
	(*ProtoBufStackMultiMessage)(nil),    // 1: golang.example.policy.ProtoBufStackMultiMessage
}
var file_protoBufStack_proto_depIdxs = []int32{
	0, // 0: golang.example.policy.ProtoBufStackMultiMessage.Messages:type_name -> golang.example.policy.ProtoBufStackMessageInstance
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protoBufStack_proto_init() }
func file_protoBufStack_proto_init() {
	if File_protoBufStack_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoBufStack_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoBufStackMessageInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoBufStack_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoBufStackMultiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoBufStack_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoBufStack_proto_goTypes,
		DependencyIndexes: file_protoBufStack_proto_depIdxs,
		MessageInfos:      file_protoBufStack_proto_msgTypes,
	}.Build()
	File_protoBufStack_proto = out.File
	file_protoBufStack_proto_rawDesc = nil
	file_protoBufStack_proto_goTypes = nil
	file_protoBufStack_proto_depIdxs = nil
}

// Typecode generated from: "ProtoBufStackMessageInstance"
const ProtoBufStackMessageInstanceTypeCode uint32 = 1126111152

// Typecode generated from: "ProtoBufStackMultiMessage"
const ProtoBufStackMultiMessageTypeCode uint32 = 1367511126

//true
//true
//false
//false
type ProtoBufStackMessageInstanceWrapper struct {
	goprotoextra.BaseMessageWrapper
	Data *ProtoBufStackMessageInstance
}

func (self *ProtoBufStackMessageInstanceWrapper) Message() interface{} {
	return self.Data
}

func (self *ProtoBufStackMessageInstanceWrapper) messageWrapper() interface{} {
	return self
}

func NewProtoBufStackMessageInstanceWrapper(
	data *ProtoBufStackMessageInstance) *ProtoBufStackMessageInstanceWrapper {
	return &ProtoBufStackMessageInstanceWrapper{
		BaseMessageWrapper: goprotoextra.NewBaseMessageWrapper(),
		Data:               data,
	}
}

var _ = stream.Register(
	ProtoBufStackMessageInstanceTypeCode,
	stream.TypeCodeData{
		CreateMessage: func() proto.Message {
			return &ProtoBufStackMessageInstance{}
		},
		CreateWrapper: func(
			data proto.Message) (goprotoextra.IMessageWrapper, error) {
			if msg, ok := data.(*ProtoBufStackMessageInstance); ok {
				return NewProtoBufStackMessageInstanceWrapper(
					msg), nil
			}
			return nil, goerrors.InvalidParam
		}})

//true
//true
//false
//false
type ProtoBufStackMultiMessageWrapper struct {
	goprotoextra.BaseMessageWrapper
	Data *ProtoBufStackMultiMessage
}

func (self *ProtoBufStackMultiMessageWrapper) Message() interface{} {
	return self.Data
}

func (self *ProtoBufStackMultiMessageWrapper) messageWrapper() interface{} {
	return self
}

func NewProtoBufStackMultiMessageWrapper(
	data *ProtoBufStackMultiMessage) *ProtoBufStackMultiMessageWrapper {
	return &ProtoBufStackMultiMessageWrapper{
		BaseMessageWrapper: goprotoextra.NewBaseMessageWrapper(),
		Data:               data,
	}
}

var _ = stream.Register(
	ProtoBufStackMultiMessageTypeCode,
	stream.TypeCodeData{
		CreateMessage: func() proto.Message {
			return &ProtoBufStackMultiMessage{}
		},
		CreateWrapper: func(
			data proto.Message) (goprotoextra.IMessageWrapper, error) {
			if msg, ok := data.(*ProtoBufStackMultiMessage); ok {
				return NewProtoBufStackMultiMessageWrapper(
					msg), nil
			}
			return nil, goerrors.InvalidParam
		}})
